trainer:
  num_nodes: null
  devices: 1
model:
  class_path: dpat.extract_features.models.SimCLR
  init_args:
    backbone: shufflenetv2_w1 # Load a model from https://github.com/osmr/imgclsmob/tree/master/pytorch
    pretrained: false # Want it to be pretrained on ImageNet?
data:
  init_args:
    model: simclr
    root_dir: /scistor/guest/sjg203/projects/pmc-hhg/images-tif
    train_img_paths_and_targets: /scistor/guest/sjg203/projects/pmc-hhg/images-tif/splits/medulloblastoma+pilocytic-astrocytoma_pmc-hhg_train-subfold-0-fold-0.csv
    val_img_paths_and_targets: /scistor/guest/sjg203/projects/pmc-hhg/images-tif/splits/medulloblastoma+pilocytic-astrocytoma_pmc-hhg_val-subfold-0-fold-0.csv
    test_img_paths_and_targets: /scistor/guest/sjg203/projects/pmc-hhg/images-tif/splits/medulloblastoma+pilocytic-astrocytoma_pmc-hhg_test-subfold-0-fold-0.csv
    color_jitter: true
    num_workers: 4
    batch_size: 1024
