class_path: dpat.mil.models.VarAttention
init_args:
  in_features: 1024  # Depends on output of the (pretrained) ResNet
  hidden_features: 128
  num_classes: ${data.init_args.num_classes}
  dropout: 0.32533033076326434
  lr: 0.00014656553886225324
  momentum: 0.2713490317738959
  wd: 0.20651425578959234
  T_max: ${trainer.max_epochs}
