root_dir: "D:/Pediatric brain tumours/images-tif"
train_img_paths_and_targets: "D:/Pediatric brain tumours/images-tif/splits/medulloblastoma+pilocytic-astrocytoma_pmc-hhg_train-subfold-0-fold-0.csv"
val_img_paths_and_targets: "D:/Pediatric brain tumours/images-tif/splits/medulloblastoma+pilocytic-astrocytoma_pmc-hhg_val-subfold-0-fold-0.csv"
test_img_paths_and_targets: "D:/Pediatric brain tumours/images-tif/splits/medulloblastoma+pilocytic-astrocytoma_pmc-hhg_test-subfold-0-fold-0.csv"
mpp: 0.2
tile_size_x: 224
tile_size_y: 224
tile_overlap_x: 224
tile_overlap_y: 224
tile_mode: overflow
crop: true
num_workers: 0
batch_size: 16
