name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # test:
  #   name: Python ${{ matrix.python-version }} tests
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, macos-latest, windows-latest]
  #       python-version: ["3.8", "3.9", "3.10", "3.11"]
  #       exclude:
  #         # Pytorch is not supported on windows python>3.10.
  #         - os: windows-latest
  #           python-version: ["3.10", "3.11"]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-python@v2
  #       with:
  #         python-version: 3.9
  #     - uses: isort/isort-action@master
  #     - uses: psf/black@stable

  release:
    runs-on: ubuntu-latest
    concurrency: release

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Python Semantic Release
      uses: python-semantic-release/python-semantic-release@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}